#!/usr/bin/python
import os
import time

#lets install some software
#reminder :: vim autocomplete via 'Ctrl' + 'N'
os.system('sudo apt-get update')
os.system('sudo apt-get upgrade -y')
os.system('sudo apt-get dist-upgrade')
os.system('sudo apt-get install ipython -y')
os.system('sudo apt-get install git')
os.system('sudo apt-get install chromium-browser')
os.system('wget https://wallpaper.wiki/wp-content/uploads/2017/04/wallpaper.wiki-Beautiful-Geek-Wallpaper-PIC-WPD004360.jpg')
os.system('gsettings set org.gnome.desktop.background picture-uri "file:///home/just/Downloads/wallpaper.wiki-Beautiful-Geek-Wallpaper-PIC-WPD004360.jpg"')
os.system('sudo apt-get update')
os.system('sudo apt-get upgrade')
os.system('sudo apt-get install net-tools')
os.system('sudo apt-get install gparted')
os.system('sudo apt autoremove')

